-------------------------------- MODULE CBOR --------------------------------
(***************************************************************************)
(* Encodes TLA+ values as CBOR (RFC 8949), either as a sequence of bytes   *)
(* or in a file, and decodes them back.  A value v that ToCBOR accepts     *)
(* survives the round trip                                                 *)
(*                                                                         *)
(*     FromCBOR(ToCBOR(v)) = v                                             *)
(*     CBORSerialize(f, v) => CBORDeserialize(f) = v                       *)
(*                                                                         *)
(* if TLC can compare the elements of every set in v with each other, and  *)
(* likewise the elements of every function's domain.  TLC cannot compare 1 *)
(* with "a", so ToCBOR writes {1, "a"} and FromCBOR rejects the bytes.     *)
(*                                                                         *)
(* TLC implements all four operators in Java (tlc2.overrides.CBOR in the   *)
(* CommunityModules).  The definitions below only stop TLC with an error   *)
(* message when that implementation is not on TLC's classpath.             *)
(*                                                                         *)
(* Encoding.  Every value has exactly one encoding, so values that TLC     *)
(* considers equal are written as identical bytes:                         *)
(*                                                                         *)
(*   integer             CBOR integer (major type 0 or 1)                  *)
(*   TRUE, FALSE         CBOR true, false                                  *)
(*   string              CBOR text string (UTF-8)                          *)
(*   model value         tag 39 around its name as a text string           *)
(*   set                 tag 258 around an array of its elements           *)
(*   function f with DOMAIN f = 1..n, including every sequence, every      *)
(*   tuple, and the empty function                                         *)
(*                       array of f[1], ..., f[n]                          *)
(*   function f whose domain is a non-empty set of strings (a record)      *)
(*                       map from each x \in DOMAIN f to f[x]              *)
(*   any other function f                                                  *)
(*                       tag 33000 around an array of the pairs            *)
(*                       [x, f[x]], one for each x \in DOMAIN f            *)
(*                                                                         *)
(* IANA has registered tags 39 and 258.  Tag 33000 is not registered yet;  *)
(* it lies in the First Come First Served range.                           *)
(*                                                                         *)
(* The elements of a set, the keys of a map, and the pairs of tag 33000    *)
(* are sorted by their encoded bytes (RFC 8949, section 4.2.1).  10        *)
(* precedes 100, which precedes -1, because their encodings are 0a, 18 64, *)
(* and 20.  This is neither the order of the values nor the shortest-first *)
(* order of RFC 7049, which puts -1 before 100.  Integers and lengths use  *)
(* their shortest form, and all lengths are definite.                      *)
(*                                                                         *)
(* A CBOR map always holds a record, so a decoder in any language can      *)
(* read it into a native dictionary or struct with string keys.  Every     *)
(* other function uses tag 33000, because a map with other keys does not   *)
(* survive every decoder.  Go's fxamacker/cbor rejects a map key that is   *)
(* an array, and a JavaScript object turns every key into a string.        *)
(*                                                                         *)
(* The form of a function follows its domain alone.  [x \in S |-> 0] is    *)
(* an array if S = {} or S = 1..3, a map if S = {"a"}, and tag 33000 if    *)
(* S = {1, 3} or S is a set of model values.  A variable that holds a      *)
(* function can therefore change form from one state to the next, and an   *)
(* empty record arrives as the empty array.  A reader must accept an       *)
(* array, a map, and tag 33000 wherever the spec has a function.           *)
(*                                                                         *)
(* Producers in other languages need not sort anything, because FromCBOR   *)
(* and CBORDeserialize read elements, keys, and pairs in any order.  A     *)
(* producer that wants byte-identical output must sort by encoded bytes    *)
(* itself.  The "canonical" mode of a CBOR library does not do that.  Such *)
(* a mode sorts the keys of a map, where both orders agree because the     *)
(* keys are strings, but it leaves the pairs of tag 33000 as given,        *)
(* and Python's cbor2 sorts the elements of a set shortest-first.          *)
(*                                                                         *)
(* FromCBOR and CBORDeserialize also read integers and lengths that are    *)
(* not in shortest form, and maps whose keys are not strings.  They reject *)
(* duplicate set elements and duplicate keys, integers that TLC cannot     *)
(* represent (outside -2^31 .. 2^31-1), floating-point numbers, byte       *)
(* strings, null, undefined, indefinite lengths, other tags, invalid       *)
(* UTF-8, data items nested more than 512 deep, and bytes after the first  *)
(* data item.  ToCBOR and CBORSerialize refuse a value that nests deeper.  *)
(* A tag is a data item, so an integer can lie inside at most 511          *)
(* sequences or records, 255 sets, or 170 functions that use tag 33000.    *)
(* A model value must be defined in the model (for example in the          *)
(* configuration file); neither operator creates one.                      *)
(***************************************************************************)

LOCAL INSTANCE TLC

(***************************************************************************)
(* The CBOR encoding of value as a sequence of integers in 0..255, one per *)
(* byte.  If value cannot be encoded (an infinite set, an operator, a      *)
(* string that is not valid Unicode, a value nested too deep), TLC reports *)
(* an error.                                                               *)
(***************************************************************************)
ToCBOR(value) ==
  Assert(FALSE, "ToCBOR needs CommunityModules.jar on TLC's classpath.")

(***************************************************************************)
(* The TLA+ value of the CBOR data item in bytes, a sequence of integers   *)
(* in 0..255.                                                              *)
(***************************************************************************)
FromCBOR(bytes) ==
  Assert(FALSE, "FromCBOR needs CommunityModules.jar on TLC's classpath.")

(***************************************************************************)
(* Writes the bytes of ToCBOR(value) to the file absoluteFilename and      *)
(* equals TRUE.  Creates missing parent directories and replaces an        *)
(* existing file.  If value cannot be encoded, TLC reports an error and    *)
(* leaves the file untouched.                                              *)
(***************************************************************************)
CBORSerialize(absoluteFilename, value) ==
  Assert(FALSE, "CBORSerialize needs CommunityModules.jar on TLC's classpath.")

(***************************************************************************)
(* FromCBOR applied to the bytes of the file absoluteFilename.             *)
(***************************************************************************)
CBORDeserialize(absoluteFilename) ==
  Assert(FALSE, "CBORDeserialize needs CommunityModules.jar on TLC's classpath.")

=============================================================================
