-------------------------------- MODULE CBOR --------------------------------
(***************************************************************************)
(* Encodes TLA+ values as CBOR (RFC 8949), either as a sequence of bytes   *)
(* or in a file, and decodes them back.  Any finite TLA+ value v survives  *)
(* the round trip:                                                         *)
(*                                                                         *)
(*     FromCBOR(ToCBOR(v)) = v                                             *)
(*     CBORSerialize(f, v) => CBORDeserialize(f) = v                       *)
(*                                                                         *)
(* TLC implements all four operators in Java (tlc2.overrides.CBOR in the   *)
(* CommunityModules).  The definitions below only stop TLC with an error   *)
(* message when that implementation is not on TLC's classpath.             *)
(*                                                                         *)
(* Encoding.  Every value has exactly one encoding, so values that TLC     *)
(* considers equal are written as identical bytes:                         *)
(*                                                                         *)
(*   integer             CBOR integer (major type 0 or 1)                  *)
(*   TRUE, FALSE         CBOR true, false                                  *)
(*   string              CBOR text string (UTF-8)                          *)
(*   model value         tag 39 around its name as a text string           *)
(*   set                 tag 258 around an array of its elements           *)
(*   function f with DOMAIN f = 1..n, including every sequence, every      *)
(*   tuple, and the empty function                                         *)
(*                       array of f[1], ..., f[n]                          *)
(*   function f whose domain is a non-empty set of strings (a record)      *)
(*                       map from each x \in DOMAIN f to f[x]              *)
(*   any other function f                                                  *)
(*                       tag 33000 around an array of the pairs            *)
(*                       [x, f[x]], one for each x \in DOMAIN f            *)
(*                                                                         *)
(* The elements of a set, the keys of a map, and the pairs of tag 33000    *)
(* are sorted by their encoded bytes (RFC 8949, section 4.2.1).  This is   *)
(* not length-first order: the key "z" precedes "aa", and the integer 10   *)
(* precedes -1.  Integers and lengths use their shortest form, and all     *)
(* lengths are definite.                                                   *)
(*                                                                         *)
(* A CBOR map always holds a record, so a decoder in any language can      *)
(* read it into a native dictionary or struct.  Functions keyed by         *)
(* integers, model values, tuples, sets, or records use tag 33000 because  *)
(* the default decoders of several languages (Go, JavaScript) fail on CBOR *)
(* maps whose keys are arrays or tagged items.                             *)
(*                                                                         *)
(* Producers in other languages need not sort anything, because FromCBOR   *)
(* and CBORDeserialize read elements, keys, and pairs in any order.  The   *)
(* "canonical" modes of CBOR libraries agree with this module on maps,     *)
(* whose keys are all strings, but not on sets or tag 33000, which they    *)
(* sort length-first.  A producer that wants byte-identical output must    *)
(* sort by encoded bytes as RFC 8949, section 4.2.1 says.                  *)
(*                                                                         *)
(* FromCBOR and CBORDeserialize also read integers and lengths that are    *)
(* not in shortest form, and maps whose keys are not strings.  They reject *)
(* duplicate set elements and duplicate keys, integers that TLC cannot     *)
(* represent (outside -2^31 .. 2^31-1), floating-point numbers, byte       *)
(* strings, null, undefined, indefinite lengths, other tags, invalid       *)
(* UTF-8, data items nested more than 512 deep, and bytes after the first  *)
(* data item.  A model value must be defined in the model (for example in  *)
(* the configuration file); neither operator creates one.                  *)
(***************************************************************************)

LOCAL INSTANCE TLC

(***************************************************************************)
(* The CBOR encoding of value as a sequence of integers in 0..255, one per *)
(* byte.  If value cannot be encoded (an infinite set, an operator, a      *)
(* string that is not valid Unicode), TLC reports an error.                *)
(***************************************************************************)
ToCBOR(value) ==
  Assert(FALSE, "ToCBOR needs CommunityModules.jar on TLC's classpath.")

(***************************************************************************)
(* The TLA+ value of the CBOR data item in bytes, a sequence of integers   *)
(* in 0..255.                                                              *)
(***************************************************************************)
FromCBOR(bytes) ==
  Assert(FALSE, "FromCBOR needs CommunityModules.jar on TLC's classpath.")

(***************************************************************************)
(* Writes the bytes of ToCBOR(value) to the file absoluteFilename and      *)
(* equals TRUE.  Creates missing parent directories and replaces an        *)
(* existing file.  If value cannot be encoded, TLC reports an error and    *)
(* leaves the file untouched.                                              *)
(***************************************************************************)
CBORSerialize(absoluteFilename, value) ==
  Assert(FALSE, "CBORSerialize needs CommunityModules.jar on TLC's classpath.")

(***************************************************************************)
(* FromCBOR applied to the bytes of the file absoluteFilename.             *)
(***************************************************************************)
CBORDeserialize(absoluteFilename) ==
  Assert(FALSE, "CBORDeserialize needs CommunityModules.jar on TLC's classpath.")

=============================================================================
