name: PR

on: 
 [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d%H%M')"
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml -Dtimestamp=${{steps.date.outputs.date}}
